=== IbaiSaenzDeBuruaga/E-Sports/LMSG/Fase 3/Clasificacion/dtd/clasificaciondtd.dtd
<!-- Este seria el DTD -->
<!-- Definimos el elemento padre , sus atributos y elementos -->
<!ELEMENT clasificacion (competicion*)>
<!ELEMENT competicion (nombre_competicion, nombre_juego, equipo+)>
<!ATTLIST competicion id CDATA #REQUIRED>
<!ELEMENT nombre_competicion (#PCDATA)>
<!ELEMENT nombre_juego (#PCDATA)>
<!ELEMENT equipo (nombre_equipo, victorias, puntos)>
<!ATTLIST equipo id_equipo CDATA #REQUIRED>
<!ELEMENT nombre_equipo (#PCDATA)>
<!ELEMENT victorias (#PCDATA)>
<!ELEMENT puntos (#PCDATA)>

=== IbaiSaenzDeBuruaga/E-Sports/LMSG/Fase 3/Clasificacion/dtd/clasificacion.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE clasificacion SYSTEM "clasificaciondtd.dtd">
<clasificacion>
    <competicion id="1">
        <nombre_competicion>CS2 MAJOR COPENHAGEN 2024</nombre_competicion>
        <nombre_juego>Counter-Strike series</nombre_juego>
        <equipo id_equipo="17">
            <nombre_equipo>Team Heretics</nombre_equipo>
            <victorias>9</victorias>
            <puntos>45</puntos>
        </equipo>
        <equipo id_equipo="3">
            <nombre_equipo>Evil Geniuses</nombre_equipo>
            <victorias>8</victorias>
            <puntos>18</puntos>
        </equipo>
        <equipo id_equipo="20">
            <nombre_equipo>INTZ</nombre_equipo>
            <victorias>6</victorias>
            <puntos>21</puntos>
        </equipo>
        <equipo id_equipo="10">
            <nombre_equipo>Astralis</nombre_equipo>
            <victorias>5</victorias>
            <puntos>29</puntos>
        </equipo>
        <equipo id_equipo="16">
            <nombre_equipo>Gen.G Esports</nombre_equipo>
            <victorias>5</victorias>
            <puntos>26</puntos>
        </equipo>
        <equipo id_equipo="7">
            <nombre_equipo>FaZe Clan</nombre_equipo>
            <victorias>4</victorias>
            <puntos>53</puntos>
        </equipo>
        <equipo id_equipo="13">
            <nombre_equipo>Rogue</nombre_equipo>
            <victorias>4</victorias>
            <puntos>23</puntos>
        </equipo>
        <equipo id_equipo="4">
            <nombre_equipo>Cloud9</nombre_equipo>
            <victorias>4</victorias>
            <puntos>19</puntos>
        </equipo>
        <equipo id_equipo="1">
            <nombre_equipo>Team Liquid</nombre_equipo>
            <victorias>4</victorias>
            <puntos>15</puntos>
        </equipo>
        <equipo id_equipo="2">
            <nombre_equipo>Fnatic</nombre_equipo>
            <victorias>2</victorias>
            <puntos>16</puntos>
        </equipo>
    </competicion>
    <competicion id="2">
        <nombre_competicion>LEC</nombre_competicion>
        <nombre_juego>League of Legends</nombre_juego>
        <equipo id_equipo="14">
            <nombre_equipo>Team Dignitas</nombre_equipo>
            <victorias>8</victorias>
            <puntos>20</puntos>
        </equipo>
        <equipo id_equipo="3">
            <nombre_equipo>Evil Geniuses</nombre_equipo>
            <victorias>6</victorias>
            <puntos>13</puntos>
        </equipo>
        <equipo id_equipo="12">
            <nombre_equipo>Team Envy</nombre_equipo>
            <victorias>5</victorias>
            <puntos>14</puntos>
        </equipo>
        <equipo id_equipo="6">
            <nombre_equipo>T1</nombre_equipo>
            <victorias>4</victorias>
            <puntos>18</puntos>
        </equipo>
        <equipo id_equipo="17">
            <nombre_equipo>Team Heretics</nombre_equipo>
            <victorias>3</victorias>
            <puntos>22</puntos>
        </equipo>
        <equipo id_equipo="4">
            <nombre_equipo>Cloud9</nombre_equipo>
            <victorias>3</victorias>
            <puntos>5</puntos>
        </equipo>
        <equipo id_equipo="2">
            <nombre_equipo>Fnatic</nombre_equipo>
            <victorias>1</victorias>
            <puntos>10</puntos>
        </equipo>
        <equipo id_equipo="10">
            <nombre_equipo>Astralis</nombre_equipo>
            <victorias>1</victorias>
            <puntos>8</puntos>
        </equipo>
        <equipo id_equipo="20">
            <nombre_equipo>INTZ</nombre_equipo>
            <victorias>1</victorias>
            <puntos>6</puntos>
        </equipo>
        <equipo id_equipo="1">
            <nombre_equipo>Team Liquid</nombre_equipo>
            <victorias>1</victorias>
            <puntos>3</puntos>
        </equipo>
    </competicion>
</clasificacion>
