=== IbaiSaenzDeBuruaga/E-Sports/LMSG/Fase 3/Clasificacion/xsd/clasificacionxsd.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <!-- Aqui definimos la clase padre y el tipo donde enlazaremos los elementos -->
    <xs:element name="clasificacion" type="tipoclasifi" />
    <xs:complexType name="tipoclasifi">
            <xs:sequence>
                <xs:element name="competicion" type="tipoCompeticion" maxOccurs="unbounded"/>
            </xs:sequence>
    </xs:complexType>

    <xs:complexType name="tipoCompeticion">
        <xs:sequence>
            <!-- ponemos los elementos y su atributo -->
            <xs:element name="nombre_competicion" type="xs:string"/>
            <xs:element name="nombre_juego" type="xs:string"/>
            <xs:element name="equipo" type="tipoequipo" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:int" use="required"/>
    <!-- Creamos otro complextype con elementos y su atributo -->
    </xs:complexType>
    <xs:complexType name="tipoequipo">
        <xs:sequence>
            <!-- ponemos los elementos y los atributos -->
            <xs:element name="nombre_equipo" type="xs:string"/>
            <xs:element name="victorias" type="xs:int"/>
            <xs:element name="puntos" type="xs:int"/>
        </xs:sequence>
        <xs:attribute name="id_equipo" type="xs:int" use="required"/>
    </xs:complexType>
</xs:schema>

=== IbaiSaenzDeBuruaga/E-Sports/LMSG/Fase 3/Clasificacion/xsd/clasificacion.xml
<?xml version="1.0" encoding="UTF-8"?>
<clasificacion 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="clasificacionxsd.xsd">
    <competicion id="1">
        <nombre_competicion>CS2 MAJOR COPENHAGEN 2024</nombre_competicion>
        <nombre_juego>Counter-Strike series</nombre_juego>
        <equipo id_equipo="17">
            <nombre_equipo>Team Heretics</nombre_equipo>
            <victorias>9</victorias>
            <puntos>45</puntos>
        </equipo>
        <equipo id_equipo="3">
            <nombre_equipo>Evil Geniuses</nombre_equipo>
            <victorias>8</victorias>
            <puntos>18</puntos>
        </equipo>
        <equipo id_equipo="20">
            <nombre_equipo>INTZ</nombre_equipo>
            <victorias>6</victorias>
            <puntos>21</puntos>
        </equipo>
    </competicion>
    <!-- parece que en la segunda competicion no hay datos por eso hice algunos ficticios-->
    <competicion id="2">
        <nombre_competicion>LEC</nombre_competicion>
        <nombre_juego>League of Legends</nombre_juego>
        <equipo id_equipo="10">
            <nombre_equipo>Astralis</nombre_equipo>
            <victorias>5</victorias>
            <puntos>29</puntos>
        </equipo>
        <equipo id_equipo="16">
            <nombre_equipo>Gen.G Esports</nombre_equipo>
            <victorias>5</victorias>
            <puntos>26</puntos>
        </equipo>
        <equipo id_equipo="7">
            <nombre_equipo>FaZe Clan</nombre_equipo>
            <victorias>4</victorias>
            <puntos>53</puntos>
        </equipo>
    </competicion>
</clasificacion>
